apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: user-api
  name: user-api
  namespace: default

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user-api
    spec:
      containers:
        - image: lochanavishwajith/shoppingapi_usermanagement:{{tag}}
          imagePullPolicy: Always
          name: shoppingapi-usermanagement-c82nc
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
