apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: user-api
  name: user-api
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: user-api
  type: LoadBalancer
# status:
#   loadBalancer: {}
