name: Docker Image CI

on:
  push:
    branches: [master]
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: us-central1-c
  GKE_CLUSTER: shopping-user-api
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: run shell script
        run: echo commit hash is ${{ github.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/shoppingapi_usermanagement:${{ github.sha }}
      - name: update config files in kBs
        run: sed -i.bak 's/{{tag}}/${{ github.sha }}/g' kBs/deploy.yaml && rm kBs/*.bak
      # - uses: actions-hub/kubectl@master
      #   env:
      #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      #   with:
      #     args: apply -f ./kBs
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy to GKE cluster
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{  env.GKE_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.USERAPI_KEY }}
          CLUSTER_NAME: ${{ env.GKE_CLUSTER }}
          ZONE_NAME: ${{ env.GKE_ZONE }}
        with:
          args: apply -f ./kBs
